# Site settings
title: Exiled Metadata
description: > # this means to ignore newlines until "baseurl:"
  Assorted thoughts on software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aniketschneider.github.io" # the base hostname & protocol for your site
github_username:  aniketschneider

# Build settings
markdown: kramdown
